import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mobile/app/app.dart';
import 'package:mobile/core/config/app_config.dart';
import 'package:mobile/features/auth/application/auth_providers.dart';
import 'package:mobile/features/notifications/application/notification_providers.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Throws on invalid configuration, so a misconfigured build fails at launch.
  final config = AppConfig.fromEnvironment();

  // Not every environment this app is built in has a Firebase project
  // configured (`google-services.json` / `GoogleService-Info.plist` /
  // `firebase_options.dart`, generated by `flutterfire configure` once a
  // project exists) — see `firebaseAvailableProvider`'s doc comment. Push
  // notifications degrade to a no-op rather than the app failing to start.
  var firebaseAvailable = false;
  try {
    await Firebase.initializeApp();
    firebaseAvailable = true;
  } on Object {
    firebaseAvailable = false;
  }

  runApp(
    ProviderScope(
      overrides: [
        appConfigProvider.overrideWithValue(config),
        firebaseAvailableProvider.overrideWithValue(firebaseAvailable),
        // Plugs authentication into the HTTP layer (token + refresh-on-401).
        ...authNetworkOverrides,
      ],
      child: const ServiceMarketplaceApp(),
    ),
  );
}
